# exporters/html_export.py

from __future__ import annotations

from collections import Counter
from html import escape
from typing import Any, Dict, List

from graph import AttackSurfaceGraph
from models import NodeType


def export_html(graph: AttackSurfaceGraph) -> str:
    endpoints = graph.nodes_by_type(NodeType.ENDPOINT)
    subs = graph.nodes_by_type(NodeType.SUBDOMAIN)
    url_nodes = graph.nodes_by_type(NodeType.URL)

    # --- distributions ---
    risk_counts = Counter([e.risk.value for e in endpoints])
    origin_counts = Counter([(e.metadata or {}).get("origin", "unknown") for e in endpoints])

    url_origin_counts = Counter([(u.metadata or {}).get("origin", "unknown") for u in url_nodes])

    tech_counts = Counter()
    for e in endpoints:
        for t in (e.metadata or {}).get("technologies", []) or []:
            tech_counts[t] += 1

    # subdomain reachability
    reachable = 0
    for s in subs:
        probes = (s.metadata or {}).get("probe", []) or []
        if any(p.get("ok") for p in probes):
            reachable += 1

    # sort endpoints by score desc
    endpoints_sorted = sorted(endpoints, key=lambda n: n.score, reverse=True)

    # grab dorks stored as URL node value=google_dorks
    dorks: List[Dict[str, Any]] = []
    for u in url_nodes:
        if u.value == "google_dorks":
            dorks = (u.metadata or {}).get("dorks", []) or []
            break

    def badge(text: str, bg: str) -> str:
        return f'<span class="badge" style="background:{bg}">{escape(text)}</span>'

    def risk_badge(risk: str) -> str:
        colors = {
            "critical": "#7f1d1d",
            "high": "#b91c1c",
            "medium": "#b45309",
            "low": "#166534",
            "info": "#1d4ed8",
        }
        return badge(risk, colors.get(risk, "#334155"))

    def bool_badge(val: bool) -> str:
        return badge("yes", "#166534") if val else badge("no", "#334155")

    css = """
    body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial; margin: 24px; background: #0b1220; color:#e5e7eb; }
    h1,h2,h3 { margin: 0.6em 0; }
    .small { color:#94a3b8; font-size: 13px; }
    .card { background:#0f172a; border:1px solid #243047; padding:16px; border-radius:12px; margin: 14px 0; }
    .grid { display:grid; grid-template-columns: 1fr 1fr; gap: 14px; }
    .grid3 { display:grid; grid-template-columns: 1fr 1fr 1fr; gap: 14px; }
    .badge { color:#fff; padding: 2px 8px; border-radius: 999px; font-size: 12px; margin-right: 6px; display:inline-block; }
    table { width: 100%; border-collapse: collapse; }
    th, td { text-align:left; border-bottom: 1px solid #243047; padding: 10px; vertical-align: top; }
    th { color:#93c5fd; font-weight:600; }
    a { color:#93c5fd; text-decoration:none; }
    code { background:#111827; padding:2px 6px; border-radius:8px; }
    .kpi { font-size: 28px; font-weight: 700; }
    .muted { color:#a1a1aa; }
    .pill { background:#111827; border:1px solid #243047; padding:8px 10px; border-radius:12px; margin: 6px 0; }
    """

    html: List[str] = [
        "<html>",
        "<head>",
        "<meta charset='utf-8'/>",
        "<title>Subtrace Report</title>",
        f"<style>{css}</style>",
        "</head>",
        "<body>",
        "<h1>Subtrace Attack Surface Report</h1>",
        "<div class='small'>Generated by Subtrace</div>",
    ]

    # --- KPI grid ---
    html.append("<div class='grid3'>")

    html.append("<div class='card'>")
    html.append("<div class='small'>Endpoints</div>")
    html.append(f"<div class='kpi'>{len(endpoints)}</div>")
    html.append("<div class='small muted'>URLs discovered via crawl/discovery</div>")
    html.append("</div>")

    html.append("<div class='card'>")
    html.append("<div class='small'>Subdomains</div>")
    html.append(f"<div class='kpi'>{len(subs)}</div>")
    html.append(f"<div class='small muted'>Reachable: {reachable}</div>")
    html.append("</div>")

    html.append("<div class='card'>")
    html.append("<div class='small'>Technologies</div>")
    html.append(f"<div class='kpi'>{len(tech_counts)}</div>")
    html.append("<div class='small muted'>Detected from headers/html/scripts</div>")
    html.append("</div>")

    html.append("</div>")  # grid3

    # --- Risk distribution ---
    html.append("<div class='card'>")
    html.append("<h2>Risk Distribution</h2>")
    html.append("<div>")
    for k in ["critical", "high", "medium", "low", "info"]:
        if risk_counts.get(k):
            html.append(f"{risk_badge(k)} {risk_counts[k]}")
    if not risk_counts:
        html.append("<div class='small'>(none)</div>")
    html.append("</div>")
    html.append("</div>")

    # --- Origin/provenance distribution ---
    html.append("<div class='grid'>")

    html.append("<div class='card'>")
    html.append("<h2>Endpoint Provenance</h2>")
    if origin_counts:
        for origin, cnt in origin_counts.most_common():
            html.append(f"<div class='pill'><b>{escape(origin)}</b> <span class='small'>({cnt})</span></div>")
    else:
        html.append("<div class='small'>(none)</div>")
    html.append("</div>")

    html.append("<div class='card'>")
    html.append("<h2>URL Node Provenance</h2>")
    html.append("<div class='small'>These are URL nodes (e.g. Wayback, Dorks), not necessarily crawled.</div>")
    if url_origin_counts:
        for origin, cnt in url_origin_counts.most_common():
            html.append(f"<div class='pill'><b>{escape(origin)}</b> <span class='small'>({cnt})</span></div>")
    else:
        html.append("<div class='small'>(none)</div>")
    html.append("</div>")

    html.append("</div>")  # grid

    # --- Technologies ---
    html.append("<div class='card'>")
    html.append("<h2>Technologies</h2>")
    if tech_counts:
        html.append("<ul>")
        for tech, cnt in tech_counts.most_common(40):
            html.append(f"<li><b>{escape(tech)}</b> <span class='small'>({cnt} endpoints)</span></li>")
        html.append("</ul>")
    else:
        html.append("<div class='small'>(none detected)</div>")
    html.append("</div>")

    # --- Dorks ---
    html.append("<div class='card'>")
    html.append("<h2>Google Dorks</h2>")
    html.append("<div class='small'>These are generated queries/links (Subtrace does not scrape Google results).</div>")
    if dorks:
        html.append("<table>")
        html.append("<tr><th>Name</th><th>Query</th><th>Link</th></tr>")
        for d in dorks:
            name = escape(str(d.get("name", "")))
            query = escape(str(d.get("query", "")))
            url = escape(str(d.get("url", "")))
            html.append(
                "<tr>"
                f"<td><b>{name}</b></td>"
                f"<td><code>{query}</code></td>"
                f"<td><a href='{url}' target='_blank' rel='noreferrer'>open</a></td>"
                "</tr>"
            )
        html.append("</table>")
    else:
        html.append("<div class='small'>(no dorks available)</div>")
    html.append("</div>")

    # --- Top risk endpoints table ---
    html.append("<div class='card'>")
    html.append("<h2>Top Risk Endpoints</h2>")
    html.append("<table>")
    html.append("<tr><th>URL</th><th>Origin</th><th>Status</th><th>Risk</th><th>Score</th><th>Type</th><th>Tech</th><th>Reasons</th></tr>")

    for ep in endpoints_sorted[:200]:
        m = ep.metadata or {}
        url = escape(ep.value)
        origin = escape(str(m.get("origin", "")))
        status = escape(str(m.get("status_code", "")))
        ctype = escape(str(m.get("content_type", "")))
        techs = ", ".join(m.get("technologies", []) or [])
        techs = escape(techs)
        reasons = ", ".join(m.get("risk_reasons", []) or [])
        reasons = escape(reasons)

        html.append(
            "<tr>"
            f"<td><a href='{url}' target='_blank' rel='noreferrer'>{url}</a></td>"
            f"<td><code>{origin}</code></td>"
            f"<td><code>{status}</code></td>"
            f"<td>{risk_badge(ep.risk.value)}</td>"
            f"<td><code>{ep.score}</code></td>"
            f"<td class='small'><code>{ctype}</code></td>"
            f"<td class='small'>{techs}</td>"
            f"<td class='small'>{reasons}</td>"
            "</tr>"
        )

    html.append("</table>")
    html.append("</div>")

    # --- Subdomains table (DNS + reachability) ---
    html.append("<div class='card'>")
    html.append("<h2>Subdomains (DNS + Reachability)</h2>")
    html.append("<table>")
    html.append("<tr><th>Host</th><th>DNS</th><th>Reachable</th><th>Best URL</th><th>Status</th><th>Server</th></tr>")

    def best_probe(probes: list[dict]) -> dict | None:
        if not probes:
            return None
        # prefer https OK, then http OK, then any record
        https_ok = [p for p in probes if p.get("ok") and str(p.get("url", "")).startswith("https://")]
        if https_ok:
            return https_ok[0]
        http_ok = [p for p in probes if p.get("ok") and str(p.get("url", "")).startswith("http://")]
        if http_ok:
            return http_ok[0]
        return probes[0]

    for s in sorted(subs, key=lambda n: n.value):
        m = s.metadata or {}
        dns = m.get("dns", {}) or {}
        probes = m.get("probe", []) or []

        ips = dns.get("ips", []) or []
        cname = dns.get("cname")
        dns_str = ""
        if ips:
            dns_str += "A: " + ", ".join([escape(str(x)) for x in ips])
        if cname:
            dns_str += ("<br/>" if dns_str else "") + "CNAME: " + escape(str(cname))

        bp = best_probe(probes)
        reachable_flag = any(p.get("ok") for p in probes)

        best_url = escape(str(bp.get("final_url") or bp.get("url"))) if bp else ""
        best_status = escape(str(bp.get("status_code", ""))) if bp else ""
        best_server = escape(str(bp.get("server", ""))) if bp else ""

        html.append(
            "<tr>"
            f"<td><b>{escape(s.value)}</b></td>"
            f"<td class='small'>{dns_str or '<span class=small>(none)</span>'}</td>"
            f"<td>{bool_badge(reachable_flag)}</td>"
            f"<td class='small'>{f'<a href={best_url} target=_blank rel=noreferrer>{best_url}</a>' if best_url else ''}</td>"
            f"<td><code>{best_status}</code></td>"
            f"<td class='small'>{best_server}</td>"
            "</tr>"
        )

    html.append("</table>")
    html.append("</div>")

    # --- Graph stats ---
    stats = graph.statistics()
    html.append("<div class='card'>")
    html.append("<h2>Graph Statistics</h2>")
    html.append(f"<div class='pill'>Nodes: <b>{stats.get('nodes')}</b></div>")
    html.append(f"<div class='pill'>Edges: <b>{stats.get('edges')}</b></div>")
    html.append(f"<div class='pill'>Types: <code>{escape(str(stats.get('types')))}</code></div>")
    html.append("</div>")

    html += ["</body>", "</html>"]
    return "\n".join(html)